---
- name: setup firewall
  import_tasks: firewall.yml

- name: Deploy aci
  command: >
    {{ openshift_client_binary }} apply -f {{ aci_deployment_yaml_file }}
  delegate_to: "{{ groups.oo_first_master.0 }}"
  run_once: True
